spring:
  #  h2.console:
  #    enabled: true\q
  #    path: '/console'
  datasource:
    url: 'jdbc:postgresql://ec2-54-228-125-183.eu-west-1.compute.amazonaws.com:5432/d8gu15sjgvg905'
    username: 'hjsskdvdkeukzy'
    password: '9ef3897830f781460c926e2eabd6fecd6477a49b7ca1196f87592ee60c9e8f66'
    #    username: 'im02'
    #    password: 'Thee1ahv'
    driver-class-name: 'org.postgresql.Driver'
  jpa:
    database-platform: 'org.hibernate.dialect.PostgreSQL95Dialect'
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
          show_sql: true
          format_sql: true
server:
  port: ${PORT:8080}
storage.config:
  base.path: "uploading"



